import Head from 'next/head'
import New from '../components/Sections/New'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sapro Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <New />
    </>
  )
}
